version: 2
jobs:
  test:
    docker:
      - image: circleci/node:16.3.0@sha256:0c2595e75ab3201e78a25a1c9c115c0161aaceb969605ae9129f7c0574a023bf
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run lint
      - run: npm test
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  deploy_dev:
    docker:
      - image: circleci/node:16.3.0@sha256:0c2595e75ab3201e78a25a1c9c115c0161aaceb969605ae9129f7c0574a023bf
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: npm run deploy:master

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy_dev:
          requires:
            - test
          filters:
            branches:
              only: master
